name: Test and Secure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npx standard

      - name: Minify JS files
        run: |
          npx uglify-js mitm-*.js -o minified.js

      - name: Audit for vulnerabilities
        run: npm audit --audit-level=high